version: '3.7'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: mariadb:10.6
    env_file:
      - ./db/.env
    logging:
      options:
        max-size: "5m"
        max-file: "1"
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ticket-reservation/backend:local
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - ./backend:/var/www/html
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network
  swagger-ui:
    image: nginx:1.21.0-alpine
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    volumes:
      - ./swagger-ui:/usr/share/nginx/html/doc
      - ./doc/api.yaml:/usr/share/nginx/html/doc/api.yaml
    restart: unless-stopped
    depends_on:
      - db
      - backend
    networks:
      - app-network
  proxy:
    image: nginx:1.21.0-alpine
    logging:
      options:
        max-size: "5m"
        max-file: "1"
    volumes:
      - ./proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - db
      - backend
      - swagger-ui
    networks:
      - app-network