openapi: 3.0.0
servers: []
info:
  description: Project Development
  version: 1.0.0-oas3
  title: Project Development
paths:
  /api/login:
    post:
      tags:
        - Authentication
      summary: Login
      operationId: Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/Login'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/me:
    get:
      tags:
        - Authentication
      summary: Me
      operationId: Me
      responses:
        '200':
          $ref: '#/components/responses/Me'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/users:
    get:
      tags:
        - Management
      summary: Data Users
      operationId: DataUsers
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/users/{id}:
    get:
      tags:
        - Management
      summary: Get User
      operationId: GetUser
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/users/{id}/status:
    put:
      tags:
        - Management
      summary: Change Status User
      operationId: ChangeStatusUser
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Status'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/settings:
    get:
      tags:
        - Management
      summary: Data Settings
      operationId: DataSettings
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Setting'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - Management
      summary: Bulk Update Settings
      operationId: BulkUpdateSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/Setting'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: Forbidden
    Status:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
          enum: [0, 1]
          description: |
            1 is active, 0 is inactive
          example: 1
    Date:
      type: string
      format: date
      example: "2022-08-17"
    DateTime:
      type: string
      format: date-time
      readOnly: true
      example: "2022-08-17 00:13:28.464732"
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          format: email
        email_verified_at:
          $ref: '#/components/schemas/DateTime'
        created_at:
          $ref: '#/components/schemas/DateTime'
        updated_at:
          $ref: '#/components/schemas/DateTime'
    Setting:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          readOnly: true
        conversion:
          type: string
          example: strval
          enum: [ object, intval, strval, boolval ]
          readOnly: true
        value:
          type: string
        default_value:
          type: string
          readOnly: true

  parameters:
    UserId:
      description: User Id
      in: path
      name: id
      required: true
      schema:
        type: integer

  requestBodies:
    Login:
      type: object
      required:
        - email
        - password
        - remember
      properties:
        email:
          format: email
        password:
          type: string
        remember:
          type: boolean
    Setting:
      type: object
      required:
        - builk
      properties:
        bulk:
          type: array
          items:
            $ref: '#/components/schemas/Setting'


  responses:
    Status:
      description: No Content
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status'
    NoContent:
      description: No Content
    BadRequest:
      description: Bad Request
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Unauthorized
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Forbidden
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Not found
    UnprocessableContent:
      description: Unprocessable Content. It's usually validation error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            properties:
              errors:
                type: object
                properties:
                  type: string
          example:
            message: The given data was invalid.
            errors:
              example: The example field is required.
    TooManyRequests:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: Too many requests
    InternalServerError:
      description: Internal Server Error
    Me:
      description: Me
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/User'
              - type: object
                properties:
                  created_at:
                    writeOnly: true
                  updated_at:
                    writeOnly: true